#!/usr/bin/env node
var debug = require('debug')('{name}');
var app = require('../app');
var http = require('http');

app.set('port', process.env.PORT || 3000);

var server = http.createServer(app);
var io = require('socket.io').listen(server);

// Note a connect on the server console
io.sockets.on('connection', function (socket) {
    console.log('Client is connected via socket.io');

	// add here your socket listeners and emitters.
	// socket.emit / socket.on

});

server.listen(app.get('port'), function() {
  debug('Express server listening on port ' + server.address().port);
});
